package pathutil

import (
	"path"
	"path/filepath"
	"strings"
)

// dependencyManifestBasenames lists the basenames of dependency-manifest /
// lockfile artefacts that every package manager touches as a side effect of
// installing or upgrading a library. They are unconditionally admitted
// alongside expected_paths so that a routine `npm install -D vitest`,
// `pip install ...`, `cargo add ...` etc. does not flunk an
// expected_paths check and force the planner into an extra repair cycle
// just to widen the path declaration.
//
// Inclusion criteria: the file MUST be (a) machine-generated by the
// language's package manager, (b) safe-to-commit (not a credential or
// developer-local cache), and (c) a routinely-changing artefact of
// dependency operations. Source manifests like pyproject.toml are also
// listed because they are commonly edited alongside the lockfile.
var dependencyManifestBasenames = map[string]struct{}{
	// Node / npm / yarn / pnpm
	"package.json":        {},
	"package-lock.json":   {},
	"npm-shrinkwrap.json": {},
	"yarn.lock":           {},
	"pnpm-lock.yaml":      {},
	// Go
	"go.mod": {},
	"go.sum": {},
	// Rust
	"Cargo.toml": {},
	"Cargo.lock": {},
	// Python (uv, poetry, pip, pipenv)
	"pyproject.toml":   {},
	"uv.lock":          {},
	"poetry.lock":      {},
	"Pipfile":          {},
	"Pipfile.lock":     {},
	"requirements.txt": {},
	// Ruby
	"Gemfile":      {},
	"Gemfile.lock": {},
	// PHP
	"composer.json": {},
	"composer.lock": {},
	// Elixir
	"mix.exs":  {},
	"mix.lock": {},
}

// IsDependencyManifest reports whether file (a normalised slash-path) is a
// dependency-manifest artefact admitted regardless of expected_paths.
// Match is on basename only — manifests live at the project root for
// every package manager listed here, and matching by basename catches
// monorepo workspaces (e.g. apps/web/package.json) without enumerating
// every nesting depth in the allow list.
func IsDependencyManifest(file string) bool {
	_, ok := dependencyManifestBasenames[path.Base(file)]
	return ok
}

// AllowedByExpectedPaths reports whether file falls inside one of the
// declared expected_paths ("." admits everything; a directory entry admits
// its subtree) or is a dependency manifest. This is the single
// expected-paths semantics shared by the verify runner and the A/B
// candidate-selection metrics — keep them identical so verify and Stage 2
// never disagree about what counts as a deviation.
func AllowedByExpectedPaths(file string, expectedPaths []string) bool {
	file = filepath.ToSlash(filepath.Clean(strings.TrimSpace(file)))
	if IsDependencyManifest(file) {
		return true
	}
	for _, exp := range expectedPaths {
		exp = filepath.ToSlash(filepath.Clean(strings.TrimSpace(exp)))
		if exp == "" {
			continue
		}
		if exp == "." {
			return true
		}
		exp = strings.TrimSuffix(exp, "/")
		if file == exp || strings.HasPrefix(file, exp+"/") {
			return true
		}
	}
	return false
}
